---
- name: Loading specific OS variables for {{ ansible_distribution.split(' ')[0] }}
  include_vars: "{{ ansible_distribution.split(' ')[0] }}_{{ ansible_distribution_major_version }}.yml"

- name: Installing postgresql on {{ ansible_distribution.split(' ')[0] }}
  include_tasks: install-{{ ansible_distribution.split(' ')[0] }}.yml

- name: Setting up data directory
  when: postgresql_data_dir != none
  notify: restart postgresql
  block:
    - name: Creating data directory
      file:
        path: "{{ postgresql_data_dir }}"
        state: directory
        mode: 0755
        owner: postgres
        group: postgres

    - name: Changing data directory in config file
      lineinfile:
        path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
        regexp: "^data_directory = "
        line: data_directory = '{{ postgresql_data_dir }}'

    - name: Initdb in the new directory
      command:
        cmd: su - postgres -c '/usr/lib/postgresql/{{ postgresql_version }}/bin/initdb -D {{ postgresql_data_dir }}'
        creates: "{{ postgresql_data_dir }}"
